Repository road86/bahis-data, pull requests merged in 2023-09, with the labels that each got.

#22 fix: Disease names
  Readme.md
  bahis_data_lovi_top_diagnosis.xlsx
  prep_dash/prep_data.py
Labels: bug

#24 fix: Sourcepath changed
  Readme.md
  prep_dash/prep_data.py
Labels: bug

#25 fix: Path change
  prep_dash/prep_data.py
Labels: bug

#26 feat: refactor bahis-data deployment options
  .dockerignore
  .venv/foo
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  Readme.md
  bahis1.py
  bahis_data_lovi_top_diagnosis.xlsx
  data_pipeline.py
  lookup/bahis_data_lovi_top_diagnosis.csv
  match_farm.py
  pipeline.py
  pipeline_scripts/prep_data.py
  pipeline_scripts/prep_geojson.py
  prep_dash/prep_data.py
  prep_dash/prepgeojson.py
  server-scripts/nightly.sh
  server_scripts/import_data.py
  server_scripts/init.sql
  server_scripts/nightly.sh
Labels: feature

#27 fix: change the sqlalchemy version 2 to 1.4.49
  Pipfile
  Pipfile.lock
Labels: bug, HIGH PRIORITY
